var carpet_data = {
	data:[{
		id:1,
		name: "Modern-1",
		collection: "Modern",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-1.jpg",
		thumb:"img/categories/modern/1.jpg",
		main_img:"img/categories/modern/1.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"This calm minimalist rug is a Singh Carpet exclusive and brought to you directly from India. Hand knotted of 100% viscose, it is spectacularly durable and meticulously crafted to bring a sense of peace and integrity to any home.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:2,
		name: "Modern-2",
		collection: "Modern",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-1.jpg",
		thumb:"img/categories/modern/2.jpg",
		main_img:"img/categories/modern/2.jpg",
		grid_img:[],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"This calm minimalist rug is a Singh Carpet exclusive and brought to you directly from India. Hand knotted of 100% viscose, it is spectacularly durable and meticulously crafted to bring a sense of peace and integrity to any home.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:3,
		name: "Modern-3",
		collection: "Modern",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-2.jpg",
		thumb:"img/categories/modern/3.jpg",
		main_img:"img/categories/modern/3.jpg",
		grid_img:[],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"This calm minimalist rug is a Singh Carpet exclusive and brought to you directly from India. Hand knotted of 100% viscose, it is spectacularly durable and meticulously crafted to bring a sense of peace and integrity to any home.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:4,
		name: "Modern-4",
		collection: "Modern",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-2.jpg",
		thumb:"img/categories/modern/4.jpg",
		main_img:"img/categories/modern/4.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"This calm minimalist rug is a Singh Carpet exclusive and brought to you directly from India. Hand knotted of 100% viscose, it is spectacularly durable and meticulously crafted to bring a sense of peace and integrity to any home.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:5,
		name: "Modern-5",
		collection: "Modern",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-2.jpg",
		thumb:"img/categories/modern/5.jpg",
		main_img:"img/categories/modern/5.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"This calm minimalist rug is a Singh Carpet exclusive and brought to you directly from India. Hand knotted of 100% viscose, it is spectacularly durable and meticulously crafted to bring a sense of peace and integrity to any home.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:6,
		name: "Erased-1",
		collection: "Erased",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-3.jpg",
		thumb:"img/categories/erased/1.jpg",
		main_img:"img/categories/erased/1.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"Singh Carpet is reinventing traditional motifs with creative colorations and a smoldering blend of smoky hues. These designs give the effect of a rug that has been walked on and lovingly worn in certain areas – almost like your favorite pair of blue jeans! These work well in both modern as well as transitional spaces – distinctive and an unquestionable statement maker. Hand knotted from luxurious bamboo viscose and infused with de-saturated colors – they are sure to create a sense of awe! Shy yet sophisticated, you will understand the pure luxury of these rugs only once you see them on the floor. Exclusively at Singh Carpet!",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:7,
		name: "Erased-2",
		collection: "Erased",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-3.jpg",
		thumb:"img/categories/erased/2.jpg",
		main_img:"img/categories/erased/2.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"Singh Carpet is reinventing traditional motifs with creative colorations and a smoldering blend of smoky hues. These designs give the effect of a rug that has been walked on and lovingly worn in certain areas – almost like your favorite pair of blue jeans! These work well in both modern as well as transitional spaces – distinctive and an unquestionable statement maker. Hand knotted from luxurious bamboo viscose and infused with de-saturated colors – they are sure to create a sense of awe! Shy yet sophisticated, you will understand the pure luxury of these rugs only once you see them on the floor. Exclusively at Singh Carpet!",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:8,
		name: "Erased-3",
		collection: "Erased",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-3.jpg",
		thumb:"img/categories/erased/3.jpg",
		main_img:"img/categories/erased/3.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"Singh Carpet is reinventing traditional motifs with creative colorations and a smoldering blend of smoky hues. These designs give the effect of a rug that has been walked on and lovingly worn in certain areas – almost like your favorite pair of blue jeans! These work well in both modern as well as transitional spaces – distinctive and an unquestionable statement maker. Hand knotted from luxurious bamboo viscose and infused with de-saturated colors – they are sure to create a sense of awe! Shy yet sophisticated, you will understand the pure luxury of these rugs only once you see them on the floor. Exclusively at Singh Carpet!",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:9,
		name: "Erased-4",
		collection: "Erased",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-4.jpg",
		thumb:"img/categories/erased/4.jpg",
		main_img:"img/categories/erased/4.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"Singh Carpet is reinventing traditional motifs with creative colorations and a smoldering blend of smoky hues. These designs give the effect of a rug that has been walked on and lovingly worn in certain areas – almost like your favorite pair of blue jeans! These work well in both modern as well as transitional spaces – distinctive and an unquestionable statement maker. Hand knotted from luxurious bamboo viscose and infused with de-saturated colors – they are sure to create a sense of awe! Shy yet sophisticated, you will understand the pure luxury of these rugs only once you see them on the floor. Exclusively at Singh Carpet!",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:10,
		name: "Erased-5",
		collection: "Erased",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-4.jpg",
		thumb:"img/categories/erased/5.jpg",
		main_img:"img/categories/erased/5.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"Singh Carpet is reinventing traditional motifs with creative colorations and a smoldering blend of smoky hues. These designs give the effect of a rug that has been walked on and lovingly worn in certain areas – almost like your favorite pair of blue jeans! These work well in both modern as well as transitional spaces – distinctive and an unquestionable statement maker. Hand knotted from luxurious bamboo viscose and infused with de-saturated colors – they are sure to create a sense of awe! Shy yet sophisticated, you will understand the pure luxury of these rugs only once you see them on the floor. Exclusively at Singh Carpet!",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:11,
		name: "Saumik-1",
		collection: "Saumik",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		thumb:"img/categories/saumik/1.jpg",
		main_img:"img/categories/saumik/1.jpg",
		main_img:"images/portfolio/8.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"Inspired by stunning rock and canyon landscapes, the Saumik Collection transports rooms to beautiful topographies. The fluid designs are hand-knotted in India of 100% hand-spun viscose from bamboo, ensuring a refined shine and long-lasting quality to the collection.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:12,
		name: "Saumik-2",
		collection: "Saumik",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-5.jpg",
		thumb:"img/categories/saumik/2.jpg",
		main_img:"img/categories/saumik/2.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"Inspired by stunning rock and canyon landscapes, the Saumik Collection transports rooms to beautiful topographies. The fluid designs are hand-knotted in India of 100% hand-spun viscose from bamboo, ensuring a refined shine and long-lasting quality to the collection.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:13,
		name: "Saumik-3",
		collection: "Saumik",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-6.jpg",
		thumb:"img/categories/saumik/3.jpg",
		main_img:"img/categories/saumik/3.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"Inspired by stunning rock and canyon landscapes, the Saumik Collection transports rooms to beautiful topographies. The fluid designs are hand-knotted in India of 100% hand-spun viscose from bamboo, ensuring a refined shine and long-lasting quality to the collection.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:14,
		name: "Saumik-4",
		collection: "Saumik",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-6.jpg",
		thumb:"img/categories/saumik/4.jpg",
		main_img:"img/categories/saumik/4.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"Inspired by stunning rock and canyon landscapes, the Saumik Collection transports rooms to beautiful topographies. The fluid designs are hand-knotted in India of 100% hand-spun viscose from bamboo, ensuring a refined shine and long-lasting quality to the collection.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:15,
		name: "Saumik-5",
		collection: "Saumik",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-6.jpg",
		thumb:"img/categories/saumik/5.jpg",
		main_img:"img/categories/saumik/5.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"Inspired by stunning rock and canyon landscapes, the Saumik Collection transports rooms to beautiful topographies. The fluid designs are hand-knotted in India of 100% hand-spun viscose from bamboo, ensuring a refined shine and long-lasting quality to the collection.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:16,
		name: "Classical-1",
		collection: "Classical",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-7.jpg",
		thumb:"img/categories/classic/1.jpg",
		main_img:"img/categories/classic/1.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"This beautiful carpet is meticulously hand knotted in India by master craftsman. The timeless medallion motif creates a sophisticated yet inviting space. Perfect for a great room, foyer or nestled by a fireplace, this rug is exquisite and built to last. 100% viscose.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:17,
		name: "Classical-2",
		collection: "Classical",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-7.jpg",
		thumb:"img/categories/classic/2.jpg",
		main_img:"img/categories/classic/2.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"This beautiful carpet is meticulously hand knotted in India by master craftsman. The timeless medallion motif creates a sophisticated yet inviting space. Perfect for a great room, foyer or nestled by a fireplace, this rug is exquisite and built to last. 100% viscose.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:18,
		name: "Classical-3",
		collection: "Classical",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-7.jpg",
		thumb:"img/categories/classic/3.jpg",
		main_img:"img/categories/classic/3.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"This beautiful carpet is meticulously hand knotted in India by master craftsman. The timeless medallion motif creates a sophisticated yet inviting space. Perfect for a great room, foyer or nestled by a fireplace, this rug is exquisite and built to last. 100% viscose.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:19,
		name: "Classical-4",
		collection: "Classical",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-8.jpg",
		thumb:"img/categories/classic/4.jpg",
		main_img:"img/categories/classic/4.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"This beautiful carpet is meticulously hand knotted in India by master craftsman. The timeless medallion motif creates a sophisticated yet inviting space. Perfect for a great room, foyer or nestled by a fireplace, this rug is exquisite and built to last. 100% viscose.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:20,
		name: "Classical-5",
		collection: "Classical",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-8.jpg",
		thumb:"img/categories/classic/5.jpg",
		main_img:"img/categories/classic/5.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"This beautiful carpet is meticulously hand knotted in India by master craftsman. The timeless medallion motif creates a sophisticated yet inviting space. Perfect for a great room, foyer or nestled by a fireplace, this rug is exquisite and built to last. 100% viscose.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:21,
		name: "Classical-6",
		collection: "Classical",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-8.jpg",
		thumb:"img/categories/classic/6.jpg",
		main_img:"img/categories/classic/6.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"This beautiful carpet is meticulously hand knotted in India by master craftsman. The timeless medallion motif creates a sophisticated yet inviting space. Perfect for a great room, foyer or nestled by a fireplace, this rug is exquisite and built to last. 100% viscose.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:22,
		name: "Classical-7",
		collection: "Classical",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-8.jpg",
		thumb:"img/categories/classic/7.jpg",
		main_img:"img/categories/classic/7.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"This beautiful carpet is meticulously hand knotted in India by master craftsman. The timeless medallion motif creates a sophisticated yet inviting space. Perfect for a great room, foyer or nestled by a fireplace, this rug is exquisite and built to last. 100% viscose.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:23,
		name: "Classical-8",
		collection: "Classical",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-7.jpg",
		thumb:"img/categories/classic/8.jpg",
		main_img:"img/categories/classic/8.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"This beautiful carpet is meticulously hand knotted in India by master craftsman. The timeless medallion motif creates a sophisticated yet inviting space. Perfect for a great room, foyer or nestled by a fireplace, this rug is exquisite and built to last. 100% viscose.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:24,
		name: "Classical-9",
		collection: "Classical",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-7.jpg",
		thumb:"img/categories/classic/9.jpg",
		main_img:"img/categories/classic/9.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"This beautiful carpet is meticulously hand knotted in India by master craftsman. The timeless medallion motif creates a sophisticated yet inviting space. Perfect for a great room, foyer or nestled by a fireplace, this rug is exquisite and built to last. 100% viscose.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:25,
		name: "Classical-10",
		collection: "Classical",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-7.jpg",
		thumb:"img/categories/classic/10.jpg",
		main_img:"img/categories/classic/10.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"This beautiful carpet is meticulously hand knotted in India by master craftsman. The timeless medallion motif creates a sophisticated yet inviting space. Perfect for a great room, foyer or nestled by a fireplace, this rug is exquisite and built to last. 100% viscose.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:26,
		name: "Classical-11",
		collection: "Classical",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-8.jpg",
		thumb:"img/categories/classic/11.jpg",
		main_img:"img/categories/classic/11.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"This beautiful carpet is meticulously hand knotted in India by master craftsman. The timeless medallion motif creates a sophisticated yet inviting space. Perfect for a great room, foyer or nestled by a fireplace, this rug is exquisite and built to last. 100% viscose.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:27,
		name: "Classical-12",
		collection: "Classical",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-8.jpg",
		thumb:"img/categories/classic/12.jpg",
		main_img:"img/categories/classic/12.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"This beautiful carpet is meticulously hand knotted in India by master craftsman. The timeless medallion motif creates a sophisticated yet inviting space. Perfect for a great room, foyer or nestled by a fireplace, this rug is exquisite and built to last. 100% viscose.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:28,
		name: "Classical-13",
		collection: "Classical",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-8.jpg",
		thumb:"img/categories/classic/13.jpg",
		main_img:"img/categories/classic/13.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"This beautiful carpet is meticulously hand knotted in India by master craftsman. The timeless medallion motif creates a sophisticated yet inviting space. Perfect for a great room, foyer or nestled by a fireplace, this rug is exquisite and built to last. 100% viscose.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:29,
		name: "Classical-14",
		collection: "Classical",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-8.jpg",
		thumb:"img/categories/classic/14.jpg",
		main_img:"img/categories/classic/14.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"This beautiful carpet is meticulously hand knotted in India by master craftsman. The timeless medallion motif creates a sophisticated yet inviting space. Perfect for a great room, foyer or nestled by a fireplace, this rug is exquisite and built to last. 100% viscose.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:30,
		name: "Classical-15",
		collection: "Classical",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-7.jpg",
		thumb:"img/categories/classic/15.jpg",
		main_img:"img/categories/classic/15.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"This beautiful carpet is meticulously hand knotted in India by master craftsman. The timeless medallion motif creates a sophisticated yet inviting space. Perfect for a great room, foyer or nestled by a fireplace, this rug is exquisite and built to last. 100% viscose.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:31,
		name: "Classical-16",
		collection: "Classical",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-8.jpg",
		thumb:"img/categories/classic/5.jpg",
		main_img:"img/categories/classic/5.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"This beautiful carpet is meticulously hand knotted in India by master craftsman. The timeless medallion motif creates a sophisticated yet inviting space. Perfect for a great room, foyer or nestled by a fireplace, this rug is exquisite and built to last. 100% viscose.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:32,
		name: "Classical-17",
		collection: "Classical",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-7.jpg",
		thumb:"img/categories/classic/17.jpg",
		main_img:"img/categories/classic/17.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"This beautiful carpet is meticulously hand knotted in India by master craftsman. The timeless medallion motif creates a sophisticated yet inviting space. Perfect for a great room, foyer or nestled by a fireplace, this rug is exquisite and built to last. 100% viscose.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:33,
		name: "Classical-18",
		collection: "Classical",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-8.jpg",
		thumb:"img/categories/classic/18.jpg",
		main_img:"img/categories/classic/18.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"This beautiful carpet is meticulously hand knotted in India by master craftsman. The timeless medallion motif creates a sophisticated yet inviting space. Perfect for a great room, foyer or nestled by a fireplace, this rug is exquisite and built to last. 100% viscose.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:34,
		name: "Classical-19",
		collection: "Classical",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-8.jpg",
		thumb:"img/categories/classic/19.jpg",
		main_img:"img/categories/classic/19.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"This beautiful carpet is meticulously hand knotted in India by master craftsman. The timeless medallion motif creates a sophisticated yet inviting space. Perfect for a great room, foyer or nestled by a fireplace, this rug is exquisite and built to last. 100% viscose.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:35,
		name: "Classical-20",
		collection: "Classical",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-7.jpg",
		thumb:"img/categories/classic/20.jpg",
		main_img:"img/categories/classic/20.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"This beautiful carpet is meticulously hand knotted in India by master craftsman. The timeless medallion motif creates a sophisticated yet inviting space. Perfect for a great room, foyer or nestled by a fireplace, this rug is exquisite and built to last. 100% viscose.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:36,
		name: "Classical-21",
		collection: "Classical",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-7.jpg",
		thumb:"img/categories/classic/21.jpg",
		main_img:"img/categories/classic/21.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"This beautiful carpet is meticulously hand knotted in India by master craftsman. The timeless medallion motif creates a sophisticated yet inviting space. Perfect for a great room, foyer or nestled by a fireplace, this rug is exquisite and built to last. 100% viscose.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:37,
		name: "Modern-6",
		collection: "Modern",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-1.jpg",
		thumb:"img/categories/modern/6.jpg",
		main_img:"img/categories/modern/6.jpg",
		grid_img:[],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"This calm minimalist rug is a Singh Carpet exclusive and brought to you directly from India. Hand knotted of 100% viscose, it is spectacularly durable and meticulously crafted to bring a sense of peace and integrity to any home.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:38,
		name: "Modern-7",
		collection: "Modern",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-1.jpg",
		thumb:"img/categories/modern/7.jpg",
		main_img:"img/categories/modern/7.jpg",
		grid_img:[],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"This calm minimalist rug is a Singh Carpet exclusive and brought to you directly from India. Hand knotted of 100% viscose, it is spectacularly durable and meticulously crafted to bring a sense of peace and integrity to any home.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:39,
		name: "Modern-8",
		collection: "Modern",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-1.jpg",
		thumb:"img/categories/modern/8.jpg",
		main_img:"img/categories/modern/8.jpg",
		grid_img:[],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"This calm minimalist rug is a Singh Carpet exclusive and brought to you directly from India. Hand knotted of 100% viscose, it is spectacularly durable and meticulously crafted to bring a sense of peace and integrity to any home.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:40,
		name: "Modern-9",
		collection: "Modern",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-1.jpg",
		thumb:"img/categories/modern/9.jpg",
		main_img:"img/categories/modern/9.jpg",
		grid_img:[],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"This calm minimalist rug is a Singh Carpet exclusive and brought to you directly from India. Hand knotted of 100% viscose, it is spectacularly durable and meticulously crafted to bring a sense of peace and integrity to any home.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:41,
		name: "Modern-10",
		collection: "Modern",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-2.jpg",
		thumb:"img/categories/modern/10.jpg",
		main_img:"img/categories/modern/10.jpg",
		grid_img:[],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"This calm minimalist rug is a Singh Carpet exclusive and brought to you directly from India. Hand knotted of 100% viscose, it is spectacularly durable and meticulously crafted to bring a sense of peace and integrity to any home.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:42,
		name: "Modern-11",
		collection: "Modern",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-2.jpg",
		thumb:"img/categories/modern/11.jpg",
		main_img:"img/categories/modern/11.jpg",
		grid_img:[],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"This calm minimalist rug is a Singh Carpet exclusive and brought to you directly from India. Hand knotted of 100% viscose, it is spectacularly durable and meticulously crafted to bring a sense of peace and integrity to any home.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:43,
		name: "Modern-12",
		collection: "Modern",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-2.jpg",
		thumb:"img/categories/modern/12.jpg",
		main_img:"img/categories/modern/12.jpg",
		grid_img:[],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"This calm minimalist rug is a Singh Carpet exclusive and brought to you directly from India. Hand knotted of 100% viscose, it is spectacularly durable and meticulously crafted to bring a sense of peace and integrity to any home.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:44,
		name: "Modern-13",
		collection: "Modern",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-2.jpg",
		thumb:"img/categories/modern/13.jpg",
		main_img:"img/categories/modern/13.jpg",
		grid_img:[],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"This calm minimalist rug is a Singh Carpet exclusive and brought to you directly from India. Hand knotted of 100% viscose, it is spectacularly durable and meticulously crafted to bring a sense of peace and integrity to any home.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:45,
		name: "Modern-14",
		collection: "Modern",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-2.jpg",
		thumb:"img/categories/modern/14.jpg",
		main_img:"img/categories/modern/14.jpg",
		grid_img:[],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"This calm minimalist rug is a Singh Carpet exclusive and brought to you directly from India. Hand knotted of 100% viscose, it is spectacularly durable and meticulously crafted to bring a sense of peace and integrity to any home.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:46,
		name: "Modern-15",
		collection: "Modern",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-2.jpg",
		thumb:"img/categories/modern/15.jpg",
		main_img:"img/categories/modern/15.jpg",
		grid_img:[],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"This calm minimalist rug is a Singh Carpet exclusive and brought to you directly from India. Hand knotted of 100% viscose, it is spectacularly durable and meticulously crafted to bring a sense of peace and integrity to any home.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:47,
		name: "Modern-16",
		collection: "Modern",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-1.jpg",
		thumb:"img/categories/modern/16.jpg",
		main_img:"img/categories/modern/16.jpg",
		grid_img:[],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"This calm minimalist rug is a Singh Carpet exclusive and brought to you directly from India. Hand knotted of 100% viscose, it is spectacularly durable and meticulously crafted to bring a sense of peace and integrity to any home.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:48,
		name: "Modern-17",
		collection: "Modern",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-1.jpg",
		thumb:"img/categories/modern/17.jpg",
		main_img:"img/categories/modern/17.jpg",
		grid_img:[],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"This calm minimalist rug is a Singh Carpet exclusive and brought to you directly from India. Hand knotted of 100% viscose, it is spectacularly durable and meticulously crafted to bring a sense of peace and integrity to any home.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:49,
		name: "Modern-18",
		collection: "Modern",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-1.jpg",
		thumb:"img/categories/modern/18.jpg",
		main_img:"img/categories/modern/18.jpg",
		grid_img:[],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"This calm minimalist rug is a Singh Carpet exclusive and brought to you directly from India. Hand knotted of 100% viscose, it is spectacularly durable and meticulously crafted to bring a sense of peace and integrity to any home.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:50,
		name: "Modern-19",
		collection: "Modern",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-1.jpg",
		thumb:"img/categories/modern/19.jpg",
		main_img:"img/categories/modern/19.jpg",
		grid_img:[],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"This calm minimalist rug is a Singh Carpet exclusive and brought to you directly from India. Hand knotted of 100% viscose, it is spectacularly durable and meticulously crafted to bring a sense of peace and integrity to any home.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:51,
		name: "Modern-20",
		collection: "Modern",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-1.jpg",
		thumb:"img/categories/modern/20.jpg",
		main_img:"img/categories/modern/20.jpg",
		grid_img:[],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"This calm minimalist rug is a Singh Carpet exclusive and brought to you directly from India. Hand knotted of 100% viscose, it is spectacularly durable and meticulously crafted to bring a sense of peace and integrity to any home.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:52,
		name: "Modern-21",
		collection: "Modern",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-2.jpg",
		thumb:"img/categories/modern/21.jpg",
		main_img:"img/categories/modern/21.jpg",
		grid_img:[],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"This calm minimalist rug is a Singh Carpet exclusive and brought to you directly from India. Hand knotted of 100% viscose, it is spectacularly durable and meticulously crafted to bring a sense of peace and integrity to any home.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:53,
		name: "Modern-22",
		collection: "Modern",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-1.jpg",
		thumb:"img/categories/modern/22.jpg",
		main_img:"img/categories/modern/22.jpg",
		grid_img:[],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"This calm minimalist rug is a Singh Carpet exclusive and brought to you directly from India. Hand knotted of 100% viscose, it is spectacularly durable and meticulously crafted to bring a sense of peace and integrity to any home.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:54,
		name: "Erased-6",
		collection: "Erased",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-3.jpg",
		thumb:"img/categories/erased/6.jpg",
		main_img:"img/categories/erased/6.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"Singh Carpet is reinventing traditional motifs with creative colorations and a smoldering blend of smoky hues. These designs give the effect of a rug that has been walked on and lovingly worn in certain areas – almost like your favorite pair of blue jeans! These work well in both modern as well as transitional spaces – distinctive and an unquestionable statement maker. Hand knotted from luxurious bamboo viscose and infused with de-saturated colors – they are sure to create a sense of awe! Shy yet sophisticated, you will understand the pure luxury of these rugs only once you see them on the floor. Exclusively at Singh Carpet!",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:55,
		name: "Erased-7",
		collection: "Erased",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-3.jpg",
		thumb:"img/categories/erased/7.jpg",
		main_img:"img/categories/erased/7.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"Singh Carpet is reinventing traditional motifs with creative colorations and a smoldering blend of smoky hues. These designs give the effect of a rug that has been walked on and lovingly worn in certain areas – almost like your favorite pair of blue jeans! These work well in both modern as well as transitional spaces – distinctive and an unquestionable statement maker. Hand knotted from luxurious bamboo viscose and infused with de-saturated colors – they are sure to create a sense of awe! Shy yet sophisticated, you will understand the pure luxury of these rugs only once you see them on the floor. Exclusively at Singh Carpet!",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:56,
		name: "Erased-8",
		collection: "Erased",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-3.jpg",
		thumb:"img/categories/erased/8.jpg",
		main_img:"img/categories/erased/8.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"Singh Carpet is reinventing traditional motifs with creative colorations and a smoldering blend of smoky hues. These designs give the effect of a rug that has been walked on and lovingly worn in certain areas – almost like your favorite pair of blue jeans! These work well in both modern as well as transitional spaces – distinctive and an unquestionable statement maker. Hand knotted from luxurious bamboo viscose and infused with de-saturated colors – they are sure to create a sense of awe! Shy yet sophisticated, you will understand the pure luxury of these rugs only once you see them on the floor. Exclusively at Singh Carpet!",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:57,
		name: "Erased-9",
		collection: "Erased",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-4.jpg",
		thumb:"img/categories/erased/9.jpg",
		main_img:"img/categories/erased/9.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"Singh Carpet is reinventing traditional motifs with creative colorations and a smoldering blend of smoky hues. These designs give the effect of a rug that has been walked on and lovingly worn in certain areas – almost like your favorite pair of blue jeans! These work well in both modern as well as transitional spaces – distinctive and an unquestionable statement maker. Hand knotted from luxurious bamboo viscose and infused with de-saturated colors – they are sure to create a sense of awe! Shy yet sophisticated, you will understand the pure luxury of these rugs only once you see them on the floor. Exclusively at Singh Carpet!",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:58,
		name: "Erased-10",
		collection: "Erased",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-4.jpg",
		thumb:"img/categories/erased/10.jpg",
		main_img:"img/categories/erased/10.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"Singh Carpet is reinventing traditional motifs with creative colorations and a smoldering blend of smoky hues. These designs give the effect of a rug that has been walked on and lovingly worn in certain areas – almost like your favorite pair of blue jeans! These work well in both modern as well as transitional spaces – distinctive and an unquestionable statement maker. Hand knotted from luxurious bamboo viscose and infused with de-saturated colors – they are sure to create a sense of awe! Shy yet sophisticated, you will understand the pure luxury of these rugs only once you see them on the floor. Exclusively at Singh Carpet!",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:59,
		name: "Erased-11",
		collection: "Erased",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-4.jpg",
		thumb:"img/categories/erased/11.jpg",
		main_img:"img/categories/erased/11.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"Singh Carpet is reinventing traditional motifs with creative colorations and a smoldering blend of smoky hues. These designs give the effect of a rug that has been walked on and lovingly worn in certain areas – almost like your favorite pair of blue jeans! These work well in both modern as well as transitional spaces – distinctive and an unquestionable statement maker. Hand knotted from luxurious bamboo viscose and infused with de-saturated colors – they are sure to create a sense of awe! Shy yet sophisticated, you will understand the pure luxury of these rugs only once you see them on the floor. Exclusively at Singh Carpet!",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:60,
		name: "Erased-12",
		collection: "Erased",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-4.jpg",
		thumb:"img/categories/erased/12.jpg",
		main_img:"img/categories/erased/12.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"Singh Carpet is reinventing traditional motifs with creative colorations and a smoldering blend of smoky hues. These designs give the effect of a rug that has been walked on and lovingly worn in certain areas – almost like your favorite pair of blue jeans! These work well in both modern as well as transitional spaces – distinctive and an unquestionable statement maker. Hand knotted from luxurious bamboo viscose and infused with de-saturated colors – they are sure to create a sense of awe! Shy yet sophisticated, you will understand the pure luxury of these rugs only once you see them on the floor. Exclusively at Singh Carpet!",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:61,
		name: "Erased-13",
		collection: "Erased",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-4.jpg",
		thumb:"img/categories/erased/13.jpg",
		main_img:"img/categories/erased/13.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"Singh Carpet is reinventing traditional motifs with creative colorations and a smoldering blend of smoky hues. These designs give the effect of a rug that has been walked on and lovingly worn in certain areas – almost like your favorite pair of blue jeans! These work well in both modern as well as transitional spaces – distinctive and an unquestionable statement maker. Hand knotted from luxurious bamboo viscose and infused with de-saturated colors – they are sure to create a sense of awe! Shy yet sophisticated, you will understand the pure luxury of these rugs only once you see them on the floor. Exclusively at Singh Carpet!",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:62,
		name: "Erased-14",
		collection: "Erased",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-4.jpg",
		thumb:"img/categories/erased/14.jpg",
		main_img:"img/categories/erased/14.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"Singh Carpet is reinventing traditional motifs with creative colorations and a smoldering blend of smoky hues. These designs give the effect of a rug that has been walked on and lovingly worn in certain areas – almost like your favorite pair of blue jeans! These work well in both modern as well as transitional spaces – distinctive and an unquestionable statement maker. Hand knotted from luxurious bamboo viscose and infused with de-saturated colors – they are sure to create a sense of awe! Shy yet sophisticated, you will understand the pure luxury of these rugs only once you see them on the floor. Exclusively at Singh Carpet!",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:63,
		name: "Erased-15",
		collection: "Erased",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-3.jpg",
		thumb:"img/categories/erased/15.jpg",
		main_img:"img/categories/erased/15.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"Singh Carpet is reinventing traditional motifs with creative colorations and a smoldering blend of smoky hues. These designs give the effect of a rug that has been walked on and lovingly worn in certain areas – almost like your favorite pair of blue jeans! These work well in both modern as well as transitional spaces – distinctive and an unquestionable statement maker. Hand knotted from luxurious bamboo viscose and infused with de-saturated colors – they are sure to create a sense of awe! Shy yet sophisticated, you will understand the pure luxury of these rugs only once you see them on the floor. Exclusively at Singh Carpet!",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:64,
		name: "Erased-16",
		collection: "Erased",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-3.jpg",
		thumb:"img/categories/erased/16.jpg",
		main_img:"img/categories/erased/16.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"Singh Carpet is reinventing traditional motifs with creative colorations and a smoldering blend of smoky hues. These designs give the effect of a rug that has been walked on and lovingly worn in certain areas – almost like your favorite pair of blue jeans! These work well in both modern as well as transitional spaces – distinctive and an unquestionable statement maker. Hand knotted from luxurious bamboo viscose and infused with de-saturated colors – they are sure to create a sense of awe! Shy yet sophisticated, you will understand the pure luxury of these rugs only once you see them on the floor. Exclusively at Singh Carpet!",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:65,
		name: "Erased-17",
		collection: "Erased",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-4.jpg",
		thumb:"img/categories/erased/17.jpg",
		main_img:"img/categories/erased/17.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"Singh Carpet is reinventing traditional motifs with creative colorations and a smoldering blend of smoky hues. These designs give the effect of a rug that has been walked on and lovingly worn in certain areas – almost like your favorite pair of blue jeans! These work well in both modern as well as transitional spaces – distinctive and an unquestionable statement maker. Hand knotted from luxurious bamboo viscose and infused with de-saturated colors – they are sure to create a sense of awe! Shy yet sophisticated, you will understand the pure luxury of these rugs only once you see them on the floor. Exclusively at Singh Carpet!",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:66,
		name: "Saumik-6",
		collection: "Saumik",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-6.jpg",
		thumb:"img/categories/saumik/6.jpg",
		main_img:"img/categories/saumik/6.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"Inspired by stunning rock and canyon landscapes, the Saumik Collection transports rooms to beautiful topographies. The fluid designs are hand-knotted in India of 100% hand-spun viscose from bamboo, ensuring a refined shine and long-lasting quality to the collection.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:67,
		name: "Saumik-7",
		collection: "Saumik",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-6.jpg",
		thumb:"img/categories/saumik/7.jpg",
		main_img:"img/categories/saumik/7.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"Inspired by stunning rock and canyon landscapes, the Saumik Collection transports rooms to beautiful topographies. The fluid designs are hand-knotted in India of 100% hand-spun viscose from bamboo, ensuring a refined shine and long-lasting quality to the collection.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:68,
		name: "Saumik-8",
		collection: "Saumik",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-7.jpg",
		thumb:"img/categories/saumik/8.jpg",
		main_img:"img/categories/saumik/8.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"Inspired by stunning rock and canyon landscapes, the Saumik Collection transports rooms to beautiful topographies. The fluid designs are hand-knotted in India of 100% hand-spun viscose from bamboo, ensuring a refined shine and long-lasting quality to the collection.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:69,
		name: "Saumik-9",
		collection: "Saumik",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-7.jpg",
		thumb:"img/categories/saumik/9.jpg",
		main_img:"img/categories/saumik/9.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"Inspired by stunning rock and canyon landscapes, the Saumik Collection transports rooms to beautiful topographies. The fluid designs are hand-knotted in India of 100% hand-spun viscose from bamboo, ensuring a refined shine and long-lasting quality to the collection.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:70,
		name: "Saumik-10",
		collection: "Saumik",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-7.jpg",
		thumb:"img/categories/saumik/10.jpg",
		main_img:"img/categories/saumik/10.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"Inspired by stunning rock and canyon landscapes, the Saumik Collection transports rooms to beautiful topographies. The fluid designs are hand-knotted in India of 100% hand-spun viscose from bamboo, ensuring a refined shine and long-lasting quality to the collection.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:71,
		name: "Saumik-11",
		collection: "Saumik",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-7.jpg",
		thumb:"img/categories/saumik/11.jpg",
		main_img:"img/categories/saumik/11.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"Inspired by stunning rock and canyon landscapes, the Saumik Collection transports rooms to beautiful topographies. The fluid designs are hand-knotted in India of 100% hand-spun viscose from bamboo, ensuring a refined shine and long-lasting quality to the collection.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:72,
		name: "Saumik-12",
		collection: "Saumik",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-7.jpg",
		thumb:"img/categories/saumik/12.jpg",
		main_img:"img/categories/saumik/12.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"Inspired by stunning rock and canyon landscapes, the Saumik Collection transports rooms to beautiful topographies. The fluid designs are hand-knotted in India of 100% hand-spun viscose from bamboo, ensuring a refined shine and long-lasting quality to the collection.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:73,
		name: "Saumik-13",
		collection: "Saumik",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-7.jpg",
		thumb:"img/categories/saumik/13.jpg",
		main_img:"img/categories/saumik/13.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"Inspired by stunning rock and canyon landscapes, the Saumik Collection transports rooms to beautiful topographies. The fluid designs are hand-knotted in India of 100% hand-spun viscose from bamboo, ensuring a refined shine and long-lasting quality to the collection.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:74,
		name: "Saumik-14",
		collection: "Saumik",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-6.jpg",
		thumb:"img/categories/saumik/14.jpg",
		main_img:"img/categories/saumik/14.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"Inspired by stunning rock and canyon landscapes, the Saumik Collection transports rooms to beautiful topographies. The fluid designs are hand-knotted in India of 100% hand-spun viscose from bamboo, ensuring a refined shine and long-lasting quality to the collection.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	},
	{
		id:75,
		name: "Saumik-15",
		collection: "Saumik",
		about: "Hand Knotted<br>100% Viscose From Bamboo",
		header_img: "img/headers/header-6.jpg",
		thumb:"img/categories/saumik/15.jpg",
		main_img:"img/categories/saumik/15.jpg",
		grid_img:["images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg", "images/portfolio/full-project-1.jpg"],
		pile_height:"0.38",
		size:"6.6x9.9 ft",
		quality:"100 lines",
		description:"Inspired by stunning rock and canyon landscapes, the Saumik Collection transports rooms to beautiful topographies. The fluid designs are hand-knotted in India of 100% hand-spun viscose from bamboo, ensuring a refined shine and long-lasting quality to the collection.",
		care: "Clean spills, including water, immediately by blotting with a clean sponge or cloth. Avoid exposure to all liquids. Professional cleaning recommended. Rug pad recommended for use on hard floor. Expect shedding. For vacuuming, use a vacuum cleaner without beater bar or one where you can set the bar to the highest pile setting. If your vacuum has variable power settings, set on low. Vacuum full length of the rug, turn and repeat to the next area, rather than back and forth motion."
	}]
};
function open_hashlink(){
	var url = window.location.href;
	console.log(url);
    url = url.split('#');
    console.log(url);
    if(url.length > 1){
    	var pid = carpet_open(url[1]);
    	if(!pid){
    		carpet_open(1);
    	}
    }
    else{
    	carpet_open(1);
    }
    
}
function carpet_open(id){
	
	var status = false;
	var data = carpet_data.data;

	for (var i = 0; i < data.length; i++) {

		if(data[i].id == id){
			console.log(data.length);
			status = true;
			$(".carpet-header").data("background", data[i].header_img);
			$(".carpet-collection").text(data[i].collection);
			$(".carpet-name").text(data[i].name);
			$(".carpet-about").html(data[i].about);
			$(".carpet-height").text(data[i].pile_height);
			$(".carpet-size").text(data[i].size);
			$(".carpet-quality").text(data[i].quality);
			$(".carpet-desc").text(data[i].description);
			$(".carpet-img a").attr("href", data[i].main_img);
			$(".carpet-img img").attr("src", data[i].main_img);
			//$(".carpet-care").text(data[i].care);
			var pageSection = $(".home-section, .page-section, .small-section, .split-section");
		    pageSection.each(function(indx){
		        
		        if ($(this).attr("data-background")){
		            $(this).css("background-image", "url(" + $(this).data("background") + ")");
		        }
		    });
		    if(i == 0){
		    	var prev = data.length - 1;
		    }
		    else{
		    	var prev = i;
		    }
		    if(i == data.length - 1){
		    	var next = 1;
		    }
		    else{
		    	var next = i+2;
		    }
		    $(".work-prev").attr("href", "rug-single.html#"+prev);
		    $(".work-next").attr("href", "rug-single.html#"+next);

			break;
		}

	}
	return status;
}
$(function(){
	open_hashlink();
	$(".work-prev, .work-next").on("click", function(){

		location.reload();
		$(window).scrollTop(0);
	});
});